application: beatjuiceradio
version: 1
api_version: 1
runtime: python

handlers:
- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: /.*
  script: main.py